apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-todo-app
  template:
    metadata:
      labels:
        app: node-todo-app
    spec:
      containers:
      - name: node-todo-app
        image: 533267006952.dkr.ecr.us-east-1.amazonaws.com/node-todo-app:latest-${env.BUILD_ID}  # Updated to match the dynamic image URI and tag
        ports:
        - containerPort: 8000
